name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -p${{ secrets.DB_PASSWORD }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ester1
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push MySQL image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ester1/mysql:latest

    - name: Build and push API image
      uses: docker/build-push-action@v2
      with:
        context: ./server
        push: true
        tags: ester1/project-api:latest

    - name: Build and push React app image
      uses: docker/build-push-action@v2
      with:
        context: ./client
        push: true
        tags: ester1/project-react-app:latest
