name: Publish Docker images

on:
  push:
    branches: ['main']

jobs:
  build_and_push:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/project-api:latest

      - name: Build and push React app image
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/project-react-app:latest
      
      # MySQL image is not built but directly pulled from Docker Hub
      - name: Pull MySQL image
        run: docker pull mysql:latest
