name: Build and Push Docker Images

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push MySQL image (if necessary)
      # Skip this if you're using the mysql:latest image directly from Docker Hub
      - name: Build and push MySQL image
        uses: docker/build-push-action@v2
        with:
          context: .  # Path to Dockerfile (if needed for customization)
          push: true
          tags: ester1/mysql:latest

      # Step 4: Build and push API image
      - name: Build and push API image
        uses: docker/build-push-action@v2
        with:
          context: ./server  # Path where your API Dockerfile is located
          push: true
          tags: ester1/project-api:latest

      # Step 5: Build and push React app image
      - name: Build and push React app image
        uses: docker/build-push-action@v2
        with:
          context: ./client  # Path where your React app Dockerfile is located
          push: true
          tags: ester1/project-react-app:latest
